plugins {
    id 'java'
    id 'idea'
    id 'application'
}

java {
    sourceCompatibility = '21'
}

mainClassName = 'halatsiankova.javafromscratch.App'

jar {
    manifest {
        attributes(
                'Main-Class': mainClassName
        )
    }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.10.2'

    testImplementation 'org.mockito:mockito-core:5.11.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.11.0'

    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.10.2'

    implementation 'org.postgresql:postgresql:42.7.3'

    testImplementation 'org.mockito:mockito-core:5.11.0'
}

version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
}
